AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*

Metrics/AbcSize:
  Max: 45

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 45

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Layout/LineLength:
  Max: 200

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
